### PR TITLE
Reformat exercise config files

### PR DESCRIPTION
**Pull request by kytrinyx**
This runs the `bin/configlet fmt --update` command to
reformat the exercise configs.

### CODE REVIEW

**Comment by mbtools** [comment]
Katrina, any change to existing exercises typically triggers an alert for all students. We certainly want to avoid this for trivial changes like these that improve pretty much nothing.

Please confirm that this does not impact any users

**Comment by larshp** [comment]
what is the overall plan here? throwing in a reformat of JSON seems like spam, no actual value except that maintainers needs to review it

**Comment by ErikSchierboom** [comment]
> Katrina, any change to existing exercises typically triggers an alert for all students. We certainly want to avoid this for trivial changes like these that improve pretty much nothing.
> 
> Please confirm that this does not impact any users

Students are only triggered when:

a) a solution/test/editor/invalidator file has changed from the version when the student last downloaded the exercise
b) the solution/test/editor/invalidator file paths change

As this PR does neither, students are not affected

**Comment by kytrinyx** [comment]
Sorry for the lack of context @larshp.

I've been doing a bunch of janitorial work in the various tracks and other repositories across Exercism. I was doing some updates in a track repository and the diffs were noisier than they should have been, because the `fmt` command had not been run (presumably ever, even though the tooling was released a year ago). The update that I wanted to do ended up being mixed with the updates that were purely about the normalization from the tooling. I decided to back out my change and start by doing a full run of `fmt` across all tracks so that later updates wouldn't get mixed with pure normalization stuff.

I was so far into my rabbit hole that I completely forgot to provide context in this PR.

**Comment by larshp** [comment]
is the formatting something that will be enforced by configlet? if not we'll just end up in the same situation again

**Comment by ErikSchierboom** [comment]
> is the formatting something that will be enforced by configlet? if not we'll just end up in the same situation again

It can be, if you add the following file: https://github.com/exercism/elm/blob/b5cd84ed6b845b1708098734ffe066c0ab0d318e/.github/org-wide-files-config.toml

**Comment by larshp** [comment]
what is the overall plan? are maintainers expected to run `fmt` or is it expected that all tracks enable `fmt` ?

**Comment by iHiD** [comment]
> what is the overall plan? are maintainers expected to run fmt or is it expected that all tracks enable fmt ?

Most tracks already use `fmt`. If you don't want to run it manually, you could have a GitHub action that runs if the config.json is changed, and pushes a commit with the config formatted? That may (or may not!) be something @ErikSchierboom could do with reasonable ease. Personally, I'd use a git hook that formats the file when I push. That's what I do for linting in most projects. but a GHA might be more globally easy.

The main desire is that we want to be able to do batch PRs across the org, which save maintainers having to do janitorial work, without creating confusion/noise because of formatting mismatches (as Katrina explained in her post).

**Pull request merged**
