### PR TITLE
New Exercise: Nth Prime

### PR DESCRIPTION
**Pull request by marianfoo**
## Source
https://github.com/exercism/problem-specifications/tree/main/exercises/nth-prime

## Errors on linting
Errors because of preference of inline declaration, any options here?
image

## Errors on Test
`ltcl_nth_prime->test_first_prime` is failing
image

## Unit Test in SAP
Test without Big Prime Number because of timeout, needs optimization
image

### CODE REVIEW

**Comment by larshp** [comment]
prefer_inline, disabled in https://github.com/exercism/abap/pull/52

**Comment by marianfoo** [comment]
linting is fine now

**Comment by larshp** [comment]
https://github.com/abaplint/transpiler/pull/621 for first transpiler bug

**Comment by larshp** [comment]
running, merging

**Comment by marianfoo** [comment]
> running, merging

nice! 👍

**Pull request merged**
