### PR TITLE
Switch setup to abapGit format

### PR DESCRIPTION
**Pull request by mbtools**
With this change, it's possible to develop and maintain all exercises using abapGit. 

Requires https://github.com/abapGit/abapGit/pull/5170 to support dot-folders in abapGit.

Recommended SAP package: `$EXERCISM` with prefix folder logic

Changes to this repo:
- Add `.abapGit.xml` with starting folder is `/exercises/practice/`
- Add `package.devc.xml`
- Rename example classes to be different from exercise class
- Add testclasses to examples so you can run unit tests in SAP system
- Also adds 'Clock' exercise

image

### CODE REVIEW

**Comment by larshp** [comment]
hmm

first, we cannot rename the example classes it will decouple it from the testclasses, making it impossible to do automatic testing

**Comment by mbtools** [comment]
you're sure? the example classes are names in config.json

**Review by larshp — CHANGES_REQUESTED** [review]
hmm

**Comment by larshp** [comment]
and as the exercises run outside a system, its a good opportunity to have it all outside

**Comment by larshp** [comment]
to implement an exercise, its not possible to use only abapGit, the additional files must be added some other way

**Pull request closed without merging**
