### PR TITLE
Replace line_exists with 'read table' in isogram exercise

### PR DESCRIPTION
**Pull request by marianfoo**

### CODE REVIEW

**Comment by larshp** [comment]
heh, it doesnt work, the linter wants us to use line_exists, I'll add the downport sometime, just keep this PR open 😄

**Comment by marianfoo** [comment]
> heh, it doesnt work, the linter wants us to use line_exists, I'll add the downport sometime, just keep this PR open 😄

Ok :)

**Comment by larshp** [comment]
ref #37

**Comment by marianfoo** [comment]
at least it works in exercism :)
image

**Pull request merged**
