### PR TITLE
New Exercise: Word count

### PR DESCRIPTION
**Pull request by marianfoo**
Quite a few errors in solution.
Set status to "WIP" so only maintainers see this on exercism (as documented [here](https://github.com/exercism/docs/blob/main/building/tracks/config-json.md#concept-exercises))

## Source 
https://github.com/exercism/javascript/tree/main/exercises/practice/word-count

## SAP Unit Tests
image

## ABAP Lint
Few errors

### local_testclass_location

Don´t know what that means

```sh
./exercises/practice/word-count/zcl_word_count.clas.testclass.abap[1, 7] - Place local testclass "ltcl_word_count" in the testclass include (local_testclass_location) 
```
### check_syntax

May have a problem with the `GROUP`.

```sh
./exercises/practice/word-count/.meta/zcl_word_count.clas.abap[51, 7] - Component "size" not found in structure (check_syntax)
```
### check_syntax

`return_structure` is a local type.

```sh
./exercises/practice/word-count/.meta/zcl_word_count.clas.abap[52, 7] - "return_structure" not found, findTop (check_syntax) 
```

## Run Tests in Docker

Don´t know if my docker run is faulty because there are **many** errors in the output.

image

### CODE REVIEW

**Comment by larshp** [comment]
rename file `zcl_word_count.clas.testclass.abap` to `zcl_word_count.clas.testclasses.abap`

**Comment by larshp** [comment]
LOOP AT GROUP BY does not work yet

**Comment by marianfoo** [comment]
> LOOP AT GROUP BY does not work yet

no worries, It's probably better to refactor the solution than wait for the implementation which is surely not that easy, right?

**Comment by larshp** [comment]
we'll never really know 😅 

if the exercise is most easily solved with GROUP BY, then we should wait, but 🤷‍♂️ everything has different solutions

**Comment by marianfoo** [comment]
ok, i have a look if i find a different solution

 but there is also the other error 
Is this about `VALUE` ?
image
image
image

**Comment by marianfoo** [comment]
its the code in this PR
https://github.com/exercism/abap/blob/362edd56051138dac9afd7a07e1d92788aebd113/exercises/practice/word-count/.meta/zcl_word_count.clas.abap

**Comment by marianfoo** [comment]
> @marianfoo can you paste the full code example?
> 
> Update: oh, its the original code, guess its a derived error

ah ok, would make sense

**Comment by marianfoo** [comment]
> If the obvious solution is to use `group by` then we should hold back, because it means others will try that too.
> 
> I had a look at the exercise, and can see a couple of ways. IMHO `group by` is something more savvy people are likely to try, but that's pure speculation.

You can try with a different solution :D
In any case, it is not a solution for beginners.

**Comment by pokrakam** [comment]
> You can try with a different solution :D

I didn't mean for us, of course we can find workarounds 🙂 

What I meant was caution about putting out something where the probability of people running into issues is high. Maybe put a note in the description to avoid LOOP with GROUP BY if time to resolve is unknown, or hold this in draft if we expect it can be implemented in the next week or so.

**Comment by larshp** [comment]
perhaps just wait a bit, focus on getting #87 merged, then there are 2 more ready to merge?

might leave some time for GROUP BY to be implemented  😅

**Comment by marianfoo** [comment]
> perhaps just wait a bit, focus on getting #87 merged, then there are 2 more ready to merge?
> 
> might leave some time for GROUP BY to be implemented 😅

The two others are concept exercises which need the concepts created first.
This is a "normal" exercise we can publish if it would work.

**Comment by mbtools** [comment]
I don't think `loop ... group by` is common knowledge. Seems complicated.

here's my solution:

```abap
  METHOD count_words.
    DATA(clean) = replace( val = to_lower( phrase ) sub = `'` with = `` occ = 0 ).
    clean = replace( val = clean sub = `\n` with = ` ` occ = 0 ).
    clean = replace( val = clean sub = `\t` with = ` ` occ = 0 ).
    clean = replace( val = clean regex = `[^a-z0-9]` with = ` ` occ = 0 ).

    SPLIT condense( clean ) AT ` ` INTO TABLE DATA(words).

    LOOP AT words INTO DATA(word).
      DATA(one_result) = VALUE return_structure( word = word count = 1 ).
      COLLECT one_result INTO result.
    ENDLOOP.
  ENDMETHOD.
```

this does require a change of the result type i.e. `with key word` which should be done anyway:

```abap
    TYPES:
      return_table TYPE STANDARD TABLE OF return_structure WITH KEY word.
```

PS: Since it's now an abapGit repo, this needs `package.devc.xml` and the `xml` for the class. Best to push from a SAP system using abapGit. Then copy the class files to the `.meta` folder and add the solution there (using GH or VScode). 

PPS: abaplint errors will go away with #157.

**Comment by marianfoo** [comment]
@mbtools thanks for you solution, i created the abapGit Config
it works in 1909 but unfortunately not here
image

@larshp can you please help here with the error message
image

**Comment by mbtools** [comment]
yeah, I forgot that the collect statement isn't implemented yet
https://github.com/abaplint/transpiler/blob/main/packages/transpiler/src/statements/collect.ts

simple statement in abap but lot's of things happening behind the scenes. 

you could replace it with:

```abap
DATA(one_result) = VALUE return_structure( word = word count = 1 ).
" COLLECT one_result INTO result.
READ TABLE result ASSIGNING FIELD-SYMBOL(<result>) WITH TABLE KEY word = one_result-word.
IF sy-subrc = 0.
  <result>-count = <result>-count + one_result-count.
ELSE.
  INSERT one_result INTO TABLE result.
ENDIF.
```

**Comment by marianfoo** [comment]
@mbtools green 🥳

**Review by mbtools — CHANGES_REQUESTED** [review]
just remove tests.toml, results.json

**Comment by marianfoo** [comment]
> just remove tests.toml, results.json

done

**Review by mbtools — APPROVED** [review]
Great 👍

**Comment by mbtools** [comment]
just a question of how many students will use `collect` ... @larshp can you deal with the "pressure"?

**Comment by marianfoo** [comment]
> just a question of how many students will use `collect` ... @larshp can you deal with the "pressure"?

programming in abap for 4 years, never heard of it
So i guess not that many use it?

**Comment by marianfoo** [comment]
Exercise is only and works with the solution :)
image

**Pull request merged**
