### PR TITLE
Implement Exercise: Crypto Square

### LINKED ISSUE #228: Implement Exercise: Crypto Square
[Problem specification: crypto square](https://github.com/exercism/problem-specifications/tree/main/exercises/crypto-square)

Please assign it to me.

### PR DESCRIPTION
**Pull request by Dwivedirahul44**
closes #228

### CODE REVIEW

**Comment by Dwivedirahul44** [comment]
linter is complaining about:

> ./exercises/practice/crypto-square/.meta/zcl_crypto_square.clas.abap[45, 26] - Variable "txt" not used (unused_variables) [E

Code:
```ABAP
    crypto_text = REDUCE string(
                    INIT txt TYPE string
                    FOR i = 0 UNTIL i = column
                    FOR j = 0 UNTIL j = row
                      NEXT txt &&= |{
                        COND string( WHEN ( ( j * column ) + i ) >= str_len
                                    THEN COND string( WHEN row > 1 THEN ` `
                                                                    ELSE `` )
                                    ELSE to_lower( substring( val = str
                                                              off = ( ( j * column ) + i )
                                                              len = 1 ) ) )
                        }{ COND string( WHEN j + 1 = row
                                          AND i + 1 < column
                                          AND row > 1  THEN ` `
                                        ELSE `` ) }| ).
```

**Comment by Dwivedirahul44** [comment]
I added a workarround to reduce but the CI build fails without apparent errors, am I missing something?

**Comment by Dwivedirahul44** [comment]
@larshp -  I cant seem to go past the CI which returns a generic error. I have tried different workarounds with solution but can not find the root cause. could you please help me with this? what is the cause of the error?
image

**Comment by larshp** [comment]
REDUCE, unused var => https://github.com/abaplint/abaplint/pull/2743

**Comment by larshp** [comment]
regex bugfix => https://github.com/abaplint/transpiler/pull/952

**Comment by larshp** [comment]
running :)

**Comment by Dwivedirahul44** [comment]
> REDUCE, unused var => [abaplint/abaplint#2743](https://github.com/abaplint/abaplint/pull/2743)


You are a life saver. 
I will revert the changes to the original reduce-based solution.

**Review by larshp — APPROVED** [review]

**Pull request merged**
