### PR TITLE
Implement Exercise: ETL

### LINKED ISSUE #234: implement new exercise : ETL
[Source](https://github.com/exercism/problem-specifications/tree/main/exercises/etl).

please assign it to me.

### PR DESCRIPTION
**Pull request by Dwivedirahul44**
closes #234

### CODE REVIEW

**Comment by larshp** [comment]
error message in the log, 
image

**Comment by Dwivedirahul44** [comment]
> error message in the log, image

hmm,I missed it, will replace char1 with suitable type

**Comment by larshp** [comment]
yes

there are only very few DDIC elements part of the Exercism runttime

**Comment by Dwivedirahul44** [comment]
> yes
> 
> there are only very few DDIC elements part of the Exercism runtime
> 
> https://github.com/exercism/abap-test-runner/blob/main/src/index.ts#L110-L127

thanks for the info.

**Comment by Dwivedirahul44** [comment]
there is a unit test failing which was written on assumption that the runtime will throw an exception on ITAB duplicate key.

**Comment by Dwivedirahul44** [comment]
> "name":"DUPLICATE_LETTER","status":"fail","message":"Unit test assertion failed"

**Review by larshp — APPROVED** [review]

**Pull request merged**
