### PR TITLE
Add details about file formats to docs

### PR DESCRIPTION
**Pull request by mbtools**

### CODE REVIEW

**Comment by larshp** [comment]
wondering, its not completely compatible, right? the solutions are not pulled?

another option, have a "mirror" with just the exercises, in a nice folder structure, the XML/file endings/BOMs can be auto fixed

**Comment by mbtools** [comment]
A separate repo would make it more complicated. There aren't enough ppl creating exercises to justify spending more time on this.

**Comment by larshp** [comment]
IMHO it makes it more complicated for contributors to have this repo abapGit compatible, as abapGit cannot be used to push anyhow, as there are multiple files with same filename

**Comment by larshp** [comment]
its not possible to add a new exercise using just abapGit? there are the json files, and the solution shares the same filename as the exercise class

so I consider the abapGit compatibility a feature for the students? We currently have had zero issues or questions from students installing via abapGit. We have multiple open PRs with exercises being added which has halted due to the compability

**Comment by mbtools** [comment]
Maybe there are no questions or issues because it simply works in abapGit. 

Anyway, I think it would be a missed opportunity to keep it in one repo. I have no extra time to spend on this.

**Comment by mbtools** [comment]
Won't matter anymore

**Pull request closed without merging**
