### PR TITLE
How to add logging to your test runs

### PR DESCRIPTION
**Pull request by mbtools**
Some exercises are hard to solve directly in Exercism. This method shows an example of how to log intermediate data of your test runs.

### CODE REVIEW

**Comment by larshp** [comment]
we can add a `cl_exercism->log()` which has a magic implementation and gives the output in the run log

**Comment by mbtools** [comment]
maybe call the magic class "console"... `console=>log( 'my data' ).`

**Comment by larshp** [comment]
`console=>log()` I think that can be done quite easily

**Comment by mbtools** [comment]
will update with console info once avaiable

**Comment by larshp** [comment]
console=>log awaiting approval by @exercism/maintainers-admin

**Comment by larshp** [comment]
merged,

image

**Comment by iHiD** [comment]
Great improvement. Nice work!!

**Comment by mbtools** [comment]
This is a fantastic addition, indeed! I updated the screenshots and text.

**Review by larshp — APPROVED** [review]
nice

**Pull request merged**
