### PR TITLE
New Exercise: Difference of Squares

### PR DESCRIPTION
**Pull request by Dwivedirahul44**
closes: #236

### CODE REVIEW

**Comment by Dwivedirahul44** [comment]
@larshp  - do you think it's a bug?
Below code works:
```abap
data num type i.
data num_x type i.
num = 5.
num_x = ( ( num * ( num + 1 ) ) / 2 ).
write ipow( base = num_x exp = 2 ).
```
image

But this doesn't => output 1.
```abap
data num type i.
num = 5.
write ipow( base = ( ( num * ( num + 1 ) ) / 2 ) exp = 2 ).
```
image

**Comment by mbtools** [comment]
We want to keep the repo compatible with abapGit. I'm not sure how you are editing the files but your editor is not following the rules set by `.editorconfig`. Source files `.abap` need an empty line at the end of the file. `.xml` files also need an empty line at the end and a UTF-8 BOM (0xEF,0xBB,0xBF) at the beginning of the file (note: it's not visible in GitHub). The easiest is to copy an existing `.xml` from the repo and adjust accordingly (or create the objects in an ABAP system and use abapGit to push them to the repo).

**Comment by Dwivedirahul44** [comment]
> 

@mbtools  - thanks for pointing this out, I learned something new.

**Comment by mbtools** [comment]
The files are not correct yet. You can see in https://github.com/exercism/abap/pull/242/files how I corrected some of the other files. The end-of-file is easy to add. For the BOM value, copy older XMLs for example from https://github.com/exercism/abap/tree/main/exercises/practice/hello-world.

As far as I know, VScode does not use the `.editorconfig` in the repo automatically. Try it with extension https://github.com/editorconfig/editorconfig-vscode.

**Comment by Dwivedirahul44** [comment]
> The files are not correct yet. You can see in https://github.com/exercism/abap/pull/242/files how I corrected some of the other files. The end-of-file is easy to add. For the BOM value, copy older XMLs for example from https://github.com/exercism/abap/tree/main/exercises/practice/hello-world.
> 
> As far as I know, VScode does not use the `.editorconfig` in the repo automatically. Try it with extension https://github.com/editorconfig/editorconfig-vscode.

Thank you, this helps a lot.

**Comment by Dwivedirahul44** [comment]
@mbtools @larshp   - Please review and provide feedback.

**Comment by mbtools** [comment]
Please rename the folder from `difference-of-squares` to `difference-of-squar` to avoid this error in abapGit:

image

Otherwise it looks good

**Comment by larshp** [comment]
"difference-of-squares" is the correct name of the exercise...

**Comment by mbtools** [comment]
Who cares about a folder name? :-)

**Comment by larshp** [comment]
configlet will give an error if the slug and folder does not match, https://github.com/exercism/abap/actions/runs/3410469426/jobs/5673465648

the icon is determined via the slug name

**Comment by Dwivedirahul44** [comment]
do we want to ditch the exercise?

**Comment by larshp** [comment]
@Dwivedirahul44 check conflicts

**Comment by larshp** [comment]
merge

**Pull request merged**
