### PR TITLE
Test Exercises with Docker Images in Github Action

### PR DESCRIPTION
**Pull request by marianfoo**
extend original test script to test all exercises like in exercism production enviroment
Test Run https://github.com/marianfoo/abap/runs/4741973810?check_suite_focus=true

### CODE REVIEW

**Comment by larshp** [comment]
looks good 👍

**Comment by marianfoo** [comment]
Should i add a 'Non-Docker' Version for local tests that include linting too?

**Comment by larshp** [comment]
not sure, need to think about what options we have to make the setup easier

**Comment by marianfoo** [comment]
anything else here to do?

**Comment by larshp** [comment]
need to fix the downport in abaplint before this can be merged, so it will show green

**Comment by larshp** [comment]
moving ahead, merging

**Pull request merged**
